name: TaketheStairs
favicon: null
layout_spectrum: 0.80063
typography_spectrum: 0.48583
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: TaketheStairs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#101010'
    - '#fefefe'
    - '#444444'
    - '#6c6c6c'
    - '#b9b9b9'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
