title: TaketheStairs
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.9139785
  lightness: 0.8817204
  brandStrength: 0.6774194
  brandColors:
    - '#101010'
    - '#fefefe'
    - '#444444'
    - '#6c6c6c'
    - '#b9b9b9'
  rhythmicContrast: 0.3172043
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: TaketheStairs
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.6684588
layout_spectrum: 0.8835126
